name: Testing pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:
    inputs:
      tests_scope:
        description: 'Choice of scope for running tests'
        required: true
        type: choice
        options:
          - extract_total_area tests
          - split_num_and_text tests
          - nothing
        default: 'nothing'

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-deps
        with:
          python-version: '3.11'
      - name: Run flake8
        run: flake8 .

  extract_total_area_func_tests:
    needs: flake8
    if: github.event_name == 'workflow_dispatch' && inputs.tests_scope == 'extract_total_area tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-deps
        with:
          python-version: '3.11'
      - name: Run extract_total_area function tests
        run: pytest -rsx -m extract_total_area

  split_num_and_text_func_tests:
    needs: flake8
    if: github.event_name == 'workflow_dispatch' && inputs.tests_scope == 'split_num_and_text tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-deps
        with:
          python-version: '3.11'
      - name: Run split_num_and_text function tests
        run: pytest -rsx -m split_num_and_text
