name: Run flake8 and pytest tests

on:
  workflow_dispatch:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-deps
        with:
          python-version: '3.11'
      - name: Run flake8
        run: flake8 .

  tests:
    runs-on: ubuntu-latest
    needs: flake8
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-deps
        with:
          python-version: '3.11'
      - name: Run pytest tests
        run: pytest -rsx
