name: Run flake8 lint check

on:
  workflow_dispatch:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-deps
        with:
          python-version: '3.11'
      - name: Run flake8
        run: flake8 .
