name: Testing pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:
    inputs:
      run_extract_total_area_func_tests:
        description: 'Run extract_total_area function tests'
        required: false
        default: false
        type: boolean
      run_split_num_and_text_func_tests:
        description: 'Run split_num_and_text function tests'
        required: false
        default: false
        type: boolean

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-deps
        with:
          python-version: '3.11'
      - name: Run flake8
        run: flake8 .

  extract_total_area_func_tests:
    needs: flake8
    if: github.event_name == 'workflow_dispatch' && inputs.run_extract_total_area_func_tests == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-deps
        with:
          python-version: '3.11'
      - name: Run extract_total_area function tests
        run: pytest -rsx -m extract_total_area

  split_num_and_text_func_tests:
    needs: flake8
    if: github.event_name == 'workflow_dispatch' && inputs.run_split_num_and_text_func_tests == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-deps
        with:
          python-version: '3.11'
      - name: Run split_num_and_text function tests
        run: pytest -rsx -m split_num_and_text
